### ISSUE TITLE
How to use same script for my own

### ISSUE THREAD

**Issue by whoafridi** [deepanshu650/Question-Answering-onSQuAD-using-BERT#1]
Great notebook after all. 

I've specific questions. There is a model `sagorsarker/bangla-bert-base` already available for my language, also a squad like dataset from google `tydiqa` . So, is it possible to finetune with the model & dataset to create a new QA modules??? 
`run_squad.py` is valid for it ? or i Use `run_squad_trainer.py` ? 
I asked google but don't find anything maybe my searching also not working. Any tutorials for finuetune my own model very easily. It'll really helpful 
Thank you.

**Comment by deepanshu650** [comment]
You can finetune on that dataset but you need to see how the dataset looks like because in squad there were some different things also like id,topic  apart from article , questions,answers if that's the case you can refer to `squad.py` to see how they manage and optimize things otherwise I think you can use tokenizer and model to proceed.
And `run_squad.py` won't work on latest versions of transformers and they might make it obsolete so you need to use `run_squad_trainer.py`

**Comment by whoafridi** [comment]
Okay. Got it . Thank you again 😊
Now I've to train my own.
